/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.team3.autobattler.SceneManagement.Scenes;

import com.team3.autobattler.Game.Base.Player;
import com.team3.autobattler.Game.Base.UnitA.Unit;
import java.util.List;

/**
 *
 * @author Rio
 */
public class BuyPanel extends javax.swing.JPanel {
        Player player = Player.getPlayer();
        Unit unit;
    /**
     * Creates new form BuyPanel
     */
    public BuyPanel(Unit unit) {
        this.setOpaque(false);
        initComponents();
        this.unit = unit;
        unitNameLabel.setText( unit.getName());
        unitStatsLabel.setText(unit.getHealth() + " " + unit.getAttack() + " " +unit.getCost());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        unitStatsLabel = new javax.swing.JLabel();
        unitNameLabel = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);

        unitStatsLabel.setForeground(new java.awt.Color(255, 255, 255));
        unitStatsLabel.setText("jLabel2");
        jPanel1.add(unitStatsLabel);

        unitNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        unitNameLabel.setText("jLabel1");
        jPanel1.add(unitNameLabel);

        buyButton.setText("Purchase Unit");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(buyButton);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        // TODO add your handling code here:
        this.buyButton.setEnabled(false);
    }//GEN-LAST:event_buyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buyButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel unitNameLabel;
    private javax.swing.JLabel unitStatsLabel;
    // End of variables declaration//GEN-END:variables
}
