/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.team3.autobattler.SceneManagement.Scenes;

import com.team3.autobattler.Game.Base.UnitA.Unit;

/**
 *
 * @author Rio
 */
public class BuyPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyPanel
     */
    public BuyPanel(Unit unit) {
        initComponents();

        unitNameLabel.setText( unit.getName());
        unitStatsLabel.setText(unit.getHealth() + " " + unit.getAttack());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unitNameLabel = new javax.swing.JLabel();
        unitStatsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(5, 1));

        unitNameLabel.setText("jLabel1");
        add(unitNameLabel);

        unitStatsLabel.setText("jLabel2");
        add(unitStatsLabel);

        jLabel3.setText("jLabel3");
        add(jLabel3);

        jLabel4.setText("jLabel4");
        add(jLabel4);

        buyButton.setText("jButton1");
        add(buyButton);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel unitNameLabel;
    private javax.swing.JLabel unitStatsLabel;
    // End of variables declaration//GEN-END:variables
}
