/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.team3.autobattler.SceneManagement.Scenes;

import com.team3.autobattler.Game.Base.Player;
import com.team3.autobattler.Game.Base.UnitA.Unit;
import java.util.List;

/**
 *
 * @author Rio
 */
public class BuyPanel extends javax.swing.JPanel {
        Player player = Player.getPlayer();
        Unit unit;
    /**
     * Creates new form BuyPanel
     */
    public BuyPanel(Unit unit, byte bit) {
        initComponents();
        this.unit = unit;
        unitNameLabel.setText( unit.getName());
        unitStatsLabel.setText(unit.getHealth() + " " + unit.getAttack() + " " +unit.getCost() + "==" + bit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unitNameLabel = new javax.swing.JLabel();
        unitStatsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(5, 1));

        unitNameLabel.setText("jLabel1");
        add(unitNameLabel);

        unitStatsLabel.setText("jLabel2");
        add(unitStatsLabel);

        jLabel3.setText("jLabel3");
        add(jLabel3);

        jLabel4.setText("jLabel4");
        add(jLabel4);

        buyButton.setText("Purchase Unit");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });
        add(buyButton);
    }// </editor-fold>//GEN-END:initComponents

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        // TODO add your handling code here:
        // Validate player has enough gold to buy unit
        int size;

        List<Unit> units = player.getUnits();
        if (units == null) {
            size = 0;
        }
        else
        {
            size = units.size();
        }
    if (size < 4) {
        if (player.subtractGold(unit.getCost())) {
            player.addUnit(unit);
            System.out.println("You spent " + unit.getCost());
        }
    } else 
        {
            System.out.println("You have the max party size.");
        }
        
    }//GEN-LAST:event_buyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel unitNameLabel;
    private javax.swing.JLabel unitStatsLabel;
    // End of variables declaration//GEN-END:variables
}
