/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.team3.autobattler.SceneManagement.Scenes;

import com.team3.autobattler.AutoBattler;
import com.team3.autobattler.Game.GameStates;
import com.team3.autobattler.Network.Packet.Create.GameStateChangePacket;
import com.team3.autobattler.Network.Packet.Create.ShopEntitiesPacket;
import com.team3.autobattler.Network.Packet.Create.StartGamePacket;
import com.team3.autobattler.Network.Packet.PacketElement;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Emily
 */
public class MainMenuScene extends javax.swing.JPanel {
    private Image backgroundImage;

    /**
     * Creates new form MainMenuScene
     */
    public MainMenuScene() {
        this.backgroundImage = new ImageIcon(getClass().getResource("/spaceBackground.png")).getImage();
        Dimension size = new Dimension(backgroundImage.getWidth(null), backgroundImage.getHeight(null));
        setPreferredSize(size);
        setMinimumSize(size);
        setMaximumSize(size);
        setSize(size);
        setLayout(null);
        initComponents();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(backgroundImage, 0, 0, this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startGameButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        planet1 = new javax.swing.JLabel();
        planet2 = new javax.swing.JLabel();
        planet3 = new javax.swing.JLabel();
        currency = new javax.swing.JLabel();
        items = new javax.swing.JLabel();
        planet4 = new javax.swing.JLabel();
        welcomeUser = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(null);

        startGameButton.setText("Start Game");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });
        add(startGameButton);
        startGameButton.setBounds(468, 619, 96, 23);

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        add(logOutButton);
        logOutButton.setBounds(774, 6, 76, 23);

        planet1.setForeground(new java.awt.Color(255, 255, 255));
        planet1.setText("planet1");
        add(planet1);
        planet1.setBounds(92, 497, 43, 17);

        planet2.setForeground(new java.awt.Color(255, 255, 255));
        planet2.setText("planet2");
        add(planet2);
        planet2.setBounds(268, 497, 43, 17);

        planet3.setForeground(new java.awt.Color(255, 255, 255));
        planet3.setText("planet3");
        add(planet3);
        planet3.setBounds(653, 497, 43, 17);

        currency.setForeground(new java.awt.Color(255, 255, 255));
        currency.setText("currency");
        add(currency);
        currency.setBounds(31, 9, 50, 17);

        items.setForeground(new java.awt.Color(255, 255, 255));
        items.setText("items");
        add(items);
        items.setBounds(195, 9, 32, 17);

        planet4.setForeground(new java.awt.Color(255, 255, 255));
        planet4.setText("planet4");
        add(planet4);
        planet4.setBounds(843, 497, 43, 17);

        welcomeUser.setForeground(new java.awt.Color(255, 255, 255));
        welcomeUser.setText("welcome, *insert username*");
        add(welcomeUser);
        welcomeUser.setBounds(422, 194, 171, 44);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LAUNCH", "LOGIN", "SIGNUP", "MAINMENU", "SHOP", "GAMESEARCH", "STARTROUND", "PLAYOUTROUND", "ENDROUND", "ENDGAME" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(856, 6, 138, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        PacketElement statePacket = new GameStateChangePacket(GameStates.LOGIN);
        AutoBattler.socketHandler.sendData(statePacket);   
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        // Start Game Packet
//PacketElement statePacket = new GameStateChangePacket(GameStates.SHOP);
//        AutoBattler.socketHandler.sendData(statePacket);
        PacketElement startGame = new StartGamePacket(true);
        AutoBattler.socketHandler.sendData(startGame);   
    }//GEN-LAST:event_startGameButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        AutoBattler.socketHandler.getClient().bypassGameState(GameStates.valueOf(jComboBox1.getSelectedItem().toString()));
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel currency;
    private javax.swing.JLabel items;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel planet1;
    private javax.swing.JLabel planet2;
    private javax.swing.JLabel planet3;
    private javax.swing.JLabel planet4;
    private javax.swing.JButton startGameButton;
    public javax.swing.JLabel welcomeUser;
    // End of variables declaration//GEN-END:variables
}
