/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.team3.autobattler.SceneManagement.Scenes;

import com.team3.autobattler.Game.Base.UnitA.Unit;

/**
 *
 * @author Rio
 */
public class PlayerPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlayerPanel
     */
    public PlayerPanel() {
        this.setOpaque(false);
        initComponents();

        unitNameLabel.setText( "Buy units.");
        unitStatsLabel.setText("");
    }
    
    public PlayerPanel(Unit unit) {
        initComponents();

        unitNameLabel.setText( unit.getName());
        unitStatsLabel.setText(unit.getHealth() + " " + unit.getAttack());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        leftButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        unitNameLabel = new javax.swing.JLabel();
        unitStatsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sellButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rightButton = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setOpaque(false);

        leftButton.setText("<");
        jPanel1.add(leftButton);

        add(jPanel1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(5, 0));

        unitNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        unitNameLabel.setText("jLabel1");
        jPanel2.add(unitNameLabel);

        unitStatsLabel.setForeground(new java.awt.Color(255, 255, 255));
        unitStatsLabel.setText("jLabel2");
        jPanel2.add(unitStatsLabel);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);

        sellButton.setText("Sell Unit");
        jPanel2.add(sellButton);

        add(jPanel2);

        jPanel3.setOpaque(false);

        rightButton.setText(">");
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });
        jPanel3.add(rightButton);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JButton leftButton;
    public javax.swing.JButton rightButton;
    public javax.swing.JButton sellButton;
    private javax.swing.JLabel unitNameLabel;
    private javax.swing.JLabel unitStatsLabel;
    // End of variables declaration//GEN-END:variables
}
