/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.team3.autobattler.SceneManagement.Scenes;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Rio
 */
public class ShopScene extends javax.swing.JPanel {

    /**
     * Creates new form ShopScene
     */
    public ShopScene() {
        initComponents();
//        
//        JPanel topShopPanel = new JPanel();
//        JPanel bottomShopPanel = new JPanel();
//        
//        topShopPanel.setBackground(Color.red);
//        bottomShopPanel.setBackground(Color.blue);
//        
//        
//        JPanel clickToBuy = new JPanel();
//        
//        bottomShopPanel.setLayout(new GridLayout(1,2));
//        clickToBuy.setLayout(new GridLayout(1,4));
//        for (int i = 0; i < 4; i++) {
//            clickToBuy.add(new JButton(String.valueOf(i)));
//        }
//        
//        bottomShopPanel.add(clickToBuy);
//        bottomShopPanel.add(new JPanel());
//        add(topShopPanel);
//        add(bottomShopPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlRoot.setLayout(new javax.swing.BoxLayout(pnlRoot, javax.swing.BoxLayout.LINE_AXIS));
        add(pnlRoot, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables
}
