/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.team3.autobattler.SceneManagement.Scenes;

/**
 *
 * @author Rio
 */
public class UnconnectedScene extends javax.swing.JPanel {

    /**
     * Creates new form UnconnectedScene
     */
    public UnconnectedScene() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        unconnectedLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Could not connect to server:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jPanel1.add(jSeparator1);

        unconnectedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unconnectedLabel.setAutoscrolls(true);
        unconnectedLabel.setBorder(new javax.swing.border.MatteBorder(null));
        unconnectedLabel.setFocusable(false);
        unconnectedLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(unconnectedLabel);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel unconnectedLabel;
    // End of variables declaration//GEN-END:variables
}
