/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.team3.autobattler.SceneManagement.Scenes;

import com.team3.autobattler.Game.Base.Player;
import com.team3.autobattler.Game.Base.UnitA.Unit;
import java.awt.Image;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Emily
 */
public class UnitPanel extends javax.swing.JPanel {
        Player player = Player.getPlayer();
        Unit unit;
    /**
     * Creates new form BuyPanel
     */
    public UnitPanel(Unit unit) {
        this.setOpaque(false);
        initComponents();
        this.unit = unit;
        unitNameLabel.setText( unit.getName());
        unitHealthLabel.setText("Health: " + unit.getHealth());
        unitAttackLabel.setText("Attack: " + unit.getAttack());
        unitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/" + unit.getName() + " copy.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        unitIcon = new javax.swing.JLabel();
        unitNameLabel = new javax.swing.JLabel();
        unitHealthLabel = new javax.swing.JLabel();
        unitAttackLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        unitIcon.setBackground(new java.awt.Color(204, 204, 204));
        unitIcon.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(unitIcon);
        unitIcon.setBounds(0, 0, 110, 110);

        unitNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        unitNameLabel.setText("jLabel3");
        jPanel1.add(unitNameLabel);
        unitNameLabel.setBounds(0, 120, 110, 30);

        unitHealthLabel.setForeground(new java.awt.Color(255, 255, 255));
        unitHealthLabel.setText("jLabel2");
        jPanel1.add(unitHealthLabel);
        unitHealthLabel.setBounds(0, 160, 110, 30);

        unitAttackLabel.setForeground(new java.awt.Color(255, 255, 255));
        unitAttackLabel.setText("jLabel1");
        jPanel1.add(unitAttackLabel);
        unitAttackLabel.setBounds(0, 200, 110, 30);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel unitAttackLabel;
    private javax.swing.JLabel unitHealthLabel;
    private javax.swing.JLabel unitIcon;
    private javax.swing.JLabel unitNameLabel;
    // End of variables declaration//GEN-END:variables
}
