/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.team3.autobattler.SceneManagement;


import com.team3.autobattler.SceneManagement.Scenes.TestPane;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;




/**
 * TODO refactor into singleton
 * @author riola
 */
public class GameFrame extends javax.swing.JFrame {

    CardLayout cardLayout;
    JPanel mainPanel;    
    
    TestPane testPane;
    ConnectToServer testConnect;
    
    
    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        cardLayout = new CardLayout();
        
        mainPanel = new JPanel(cardLayout);
        
        testPane = new TestPane();
        testConnect = new ConnectToServer();
        
        // probably a better way to this than like this
        // for each panel/pane we have to add to mainPanel
        mainPanel.add(testPane, "testPane");
        mainPanel.add(testConnect, "testConnect");

        // add to jframe the mainpanel
        add(mainPanel);
        
        // Not needed?
        //initComponents();

        
        
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setLocationByPlatform(true);
        setVisible(true);
        
        
        cardLayout.show(mainPanel, "testConnect");
        
    }
    
    
    public void gameOn() {
        cardLayout.show(mainPanel, "testPane");
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
